### ISSUE TITLE
The horizontal row on full registration page should be between confirm password and country. But currently it is between the country and security question.

### ISSUE THREAD

**Issue by rahul-kumar11** [subrata1106/Release17#10]
The horizontal row on full registration page should be between confirm password and country. But currently it is between the country and security question.

**Comment by rahul-kumar11** [comment]
Duplicate to issue-13

**Comment by dharamveerSanodiya** [comment]
Changes done as per suggestion.
Duplicate issue.

**Comment by rahul-kumar11** [comment]
Retested and passed
