### ISSUE TITLE
If user try to create a new user and user select the check box of send email then the list of email template for that org should be displayed. But others template is also displaying here. 

### ISSUE THREAD

**Issue by rahul-kumar11** [subrata1106/Release17#100]
If user try to create a new user and user select the check box of send email then the list of email template for that org should be displayed. But others template is also displaying here.

**Comment by vanrajsinh-parmar** [comment]
Resolved.
cause: Inadequate Documentation

**Comment by rahul-kumar11** [comment]
retested and passed
