### ISSUE TITLE
If user is present in org and he put the teacher / org admin joining code of the org in which he is present, then user is redirected to old my home instead of giving an error message.

### ISSUE THREAD

**Issue by rahul-kumar11** [subrata1106/Release17#101]
If user is present in org and he put the teacher / org admin joining code of the org in which he is present, then user is redirected to old my home instead of giving an error message.

**Comment by vanrajsinh-parmar** [comment]
Resolved.
Cause: Inadequate Planning, Inadequate Communication (Due pending integration with new UI)

**Comment by rahul-kumar11** [comment]
retested and closed
