### ISSUE TITLE
User should not get the org admin option and message after joining org successfully same in case of teacher admin.

### ISSUE THREAD

**Issue by rahul-kumar11** [subrata1106/Release17#102]
If user user enter the valid org admin joining code of the org, then he gets the "join successfully " screen with message and "OK" button. Now if user click on "ok" user should get the Org admin option with a message in left menu.

**Comment by vanrajsinh-parmar** [comment]
Resolved. Please retest.

Cause: Others

**Comment by rahul-kumar11** [comment]
retested and passed
