### ISSUE TITLE
If a user login with cs admin and try to set any org in the context then user gets the exception.

### ISSUE THREAD

**Issue by rahul-kumar11** [subrata1106/Release17#104]
If a user login with cs admin and try to set any org in the context then user gets the exception.
![image](https://cloud.githubusercontent.com/assets/7794513/8426847/83b60350-1f30-11e5-8a32-695044ddca0b.png)

**Comment by besiddharth** [comment]
Fixed. Please validate.
Cause : Inadequate Checklist

**Comment by rahul-kumar11** [comment]
retested and passed
