### ISSUE TITLE
If downtime is set and user goes to the internal login page url in the same browser than the user is automatically logged in even if its not the the list of allowed users.

### ISSUE THREAD

**Issue by jainsmriti** [subrata1106/Release17#105]
If downtime is set and user goes to the internal login page url in the same browser than the user is automatically logged in even if its not the the list of allowed users.

![downtime](https://cloud.githubusercontent.com/assets/12691744/8427999/2058841e-1f39-11e5-8c99-8cc5b68fb806.png)

**Comment by dharamveerSanodiya** [comment]
Fixed. Please validate.

**Comment by jainsmriti** [comment]
Retested and passed.
