### ISSUE TITLE
If the user exist in the list of allowed user and user is logged in onto the system then the user does the get the Downtime message.

### ISSUE THREAD

**Issue by jainsmriti** [subrata1106/Release17#106]
If the user exist in the list of allowed user and user is logged in onto the system then the user does the get the Downtime message.
As per design doc the access to selected list of user should only be allowed via in the internal login page.

**Comment by dharamveerSanodiya** [comment]
As discussed with Nitin, XML mapped user will not redirect to the login page/Downtime page.
Please validate.
Cause: clarification

**Comment by jainsmriti** [comment]
Closed as per Discussion with Nitin.
