### ISSUE TITLE
If the LMS admin removes the downtime before its completion then the downtime should end but instead it continues till the time it was supposed to end.

### ISSUE THREAD

**Issue by jainsmriti** [subrata1106/Release17#107]
If the LMS admin removes the downtime before its completion then the downtime should end but instead it continues till the time it was supposed to end.

**Comment by dharamveerSanodiya** [comment]
Bug is resolved. Please validate.
Cause : Static list was not updating while the addition of new outage.

**Comment by jainsmriti** [comment]
Retested and passed.
