### ISSUE TITLE
If a user has parent child relationship with other ORG such that "You are currently acting as" is displayed in Welcome footer. In this case the Go to MyInfo and press Save ->Acting ORG displays from welcome header and is diaplayed if we click on MY Courses and not on ony other click 

### ISSUE THREAD

**Issue by jainsmriti** [subrata1106/Release17#108]
If a user has parent child relationship with other ORG such that "You are currently acting as" is displayed in Welcome footer. In this case the Go to MyInfo and press Save ->Acting ORG displays from welcome header and is diaplayed if we click on MY Courses and not on ony other click 

![my_info](https://cloud.githubusercontent.com/assets/12691744/8433834/c9651f96-1f65-11e5-97d5-ac4dcf1cc790.png)

**Comment by ankit-sanghvi** [comment]
fixed

**Comment by jainsmriti** [comment]
Retested and closed.
