### ISSUE TITLE
The message for the Downtime is not as per the design doc.

### ISSUE THREAD

**Issue by jainsmriti** [subrata1106/Release17#109]
The message for the Downtime is not as per the design doc.

**Comment by dharamveerSanodiya** [comment]
As discussed with nitin, we need to keep downtime message in the body part of the DownTime screen.
Cause: Suggested by Nitin

**Comment by NitinLeuva** [comment]
As discussed it should be the message provided by LMS admin.

**Comment by jainsmriti** [comment]
Retested and Passed.
