### ISSUE TITLE
On edit notification template screen when the user select the "event" (any event except the first event) then all the values will be changed according to the event except the "subject".

### ISSUE THREAD

**Issue by rahul-kumar11** [subrata1106/Release17#111]
On edit notification template screen when the user select the "event" (any event except the first event) then all the values will be changed according to the event except the "subject".

**Comment by vanrajsinh-parmar** [comment]
Resolve. Existing issue.

Cause: Others

**Comment by rahul-kumar11** [comment]
retested and passed
