### ISSUE TITLE
Please provide all error messages in same format.

### ISSUE THREAD

**Issue by rahul-kumar11** [subrata1106/Release17#12]
Please provide all error messages in same format.
![5](https://cloud.githubusercontent.com/assets/7794513/8177837/6313a4a0-1426-11e5-907f-1701fc11ee0a.png)

**Comment by dharamveerSanodiya** [comment]
Suggestion applied in the language section for English version.
Cause : Suggestion 
Source: Mentis issue : 2463

**Comment by rahul-kumar11** [comment]
retested and passed
