### ISSUE TITLE
The text marked in image is not according to the design doc on full registration page. Please change the mark text.

### ISSUE THREAD

**Issue by rahul-kumar11** [subrata1106/Release17#13]
The text marked in image is not according to the design doc. Please change the mark text.
![6](https://cloud.githubusercontent.com/assets/7794513/8179221/dd45312e-1432-11e5-89e4-642183072ede.png)

**Comment by dharamveerSanodiya** [comment]
Changes applied as per the comments.
Inherited Defects

**Comment by rahul-kumar11** [comment]
retested and passed
