### ISSUE TITLE
The text marked in image is not according to the design doc on thank you screen. Please change the mark text.

### ISSUE THREAD

**Issue by rahul-kumar11** [subrata1106/Release17#14]
The text marked in image is not according to the design doc on thank you screen. Please change the mark text.
![7](https://cloud.githubusercontent.com/assets/7794513/8179549/07e2e03c-1435-11e5-9ef3-f1066209e57a.png)

**Comment by dharamveerSanodiya** [comment]
Changes incorporated as per the comments.
Suggestion

**Comment by rahul-kumar11** [comment]
retested and passed
