### ISSUE TITLE
If a user enter a "email" in username text box on full registration page, and the email is already registered with the system then the system will provide you the suggestion for the username. These user name should be in email format.

### ISSUE THREAD

**Issue by rahul-kumar11** [subrata1106/Release17#15]
If a user enter a "email" in username text box on full registration page, and the email is already registered with the system then the system will provide you the suggestion for the username. These user name should be in email format.

**Comment by dharamveerSanodiya** [comment]
Email suggestion implemented as per the suggestion.
Suggestion

**Comment by rahul-kumar11** [comment]
retested and passed
