### ISSUE TITLE
"Forget user name or password " screen does not have the "cancel" button. The screen have cancel button in design doc.

### ISSUE THREAD

**Issue by rahul-kumar11** [subrata1106/Release17#16]
"Forget user name or password " screen does not have the "cancel" button. The screen have cancel button in design doc.

**Comment by jainsmriti** [comment]
Rectified and Committed.
Cause : Inadequate Checklist

**Comment by rahul-kumar11** [comment]
duplicate-17

**Comment by jainsmriti** [comment]
Fixed.

**Comment by rahul-kumar11** [comment]
retested and passed
