### ISSUE TITLE
The text marked in image is not according to the design doc on "Forget your user name or Password?" screen. Please change the mark text.

### ISSUE THREAD

**Issue by rahul-kumar11** [subrata1106/Release17#17]
The text marked in image is not according to the design doc on "Forget your user name or Password?" screen. Please change the mark text.
![8](https://cloud.githubusercontent.com/assets/7794513/8179976/37940876-1438-11e5-8af9-50dfb7dc7af0.png)

**Comment by jainsmriti** [comment]
Rectified and Committed.
Cause : Inadequate Checklist

**Comment by rahul-kumar11** [comment]
retested and passed
