### ISSUE TITLE
On "forget your user name and password" confirmation screen the button text should be "continue"." 

### ISSUE THREAD

**Issue by rahul-kumar11** [subrata1106/Release17#18]
On "forget your user name and password" confirmation screen the button text should be "continue"."

**Comment by jainsmriti** [comment]
Rectified and Committed.
Cause : Inadequate Checklist

**Comment by jainsmriti** [comment]
Rectified and Committed.
Cause : Inadequate Checklist

**Comment by rahul-kumar11** [comment]
retested and passed
