### ISSUE TITLE
The text marked in image is not according to the design doc on partial registration screen. Please change the mark text.

### ISSUE THREAD

**Issue by rahul-kumar11** [subrata1106/Release17#19]
The text marked in image is not according to the design doc on partial registration screen. Please change the mark text.
![9](https://cloud.githubusercontent.com/assets/7794513/8182648/22d4fe1a-144f-11e5-9df1-654caf7913a4.png)

**Comment by besiddharth** [comment]
Fixed.
Cause : Inadequate Self Review

**Comment by rahul-kumar11** [comment]
retested and passed
