### ISSUE TITLE
If a user login in the system successfully them user will be redirected to the my course screen. In left menu the my notification option with "unread count" is displayed. This count will always is zero until user does not click on "my notification" option on left menu.

### ISSUE THREAD

**Issue by rahul-kumar11** [subrata1106/Release17#21]
If a user login in the system successfully them user will be redirected to the my course screen. In left menu the my notification option with "unread count" is displayed. This count will always is zero until user does not click on "my notification" option on left menu.

**Comment by besiddharth** [comment]
Fixed.
Casue: Inadequate Checklist

**Comment by rahul-kumar11** [comment]
retested and passsed
