### ISSUE TITLE
The text marked in image is not according to the design doc on my info screen. Please change the mark text.

### ISSUE THREAD

**Issue by rahul-kumar11** [subrata1106/Release17#23]
The text marked in image is not according to the design doc on my info screen. Please change the mark text. Please change the class of the success message.
![10](https://cloud.githubusercontent.com/assets/7794513/8203378/fe1c4ed8-14fe-11e5-8311-6b71ce88035f.png)

**Comment by ankit-sanghvi** [comment]
- Fix the error messages and commit the same to source control

**Comment by rahul-kumar11** [comment]
retested and passed
