### ISSUE TITLE
The icon that is before my info heading is a link but it  should be just an icon.

### ISSUE THREAD

**Issue by rahul-kumar11** [subrata1106/Release17#24]
The icon that is before my info heading is a link but it  should be just an icon.
![11](https://cloud.githubusercontent.com/assets/7794513/8203693/52df56d4-1501-11e5-8ea0-ab9962fff4f8.png)

**Comment by ankit-sanghvi** [comment]
fixed the same.

**Comment by rahul-kumar11** [comment]
duplicate-To 23
