### ISSUE TITLE
If user hide the course, then show me select box will be available on my course screen. It have "visible" "hidden course" and "archive course" option, although there is no archive course present for the user.  

### ISSUE THREAD

**Issue by rahul-kumar11** [subrata1106/Release17#25]
If user hide the course, then show me select box will be available on my course screen. It have "visible" "hidden course" and "archive course" option, although there is no archive course present for the user.

**Comment by JB-PATEL** [comment]
Fixed. Hidden and Archieve option will display only when courses are available.

**Comment by rahul-kumar11** [comment]
Invalid bug
