### ISSUE TITLE
The text marked in images is not according to the design doc on change password screen. Please change it.

### ISSUE THREAD

**Issue by rahul-kumar11** [subrata1106/Release17#26]
The text marked in image is not according to the design doc on change password scree. Please change it.
- Errors should come after click on "save"
- after save user should redirect to my info page with success message.
![12](https://cloud.githubusercontent.com/assets/7794513/8205490/cae7ca3c-150e-11e5-966b-02a256ce028f.png)
![13](https://cloud.githubusercontent.com/assets/7794513/8205492/ceadf27c-150e-11e5-81c7-3c563ffed109.png)

**Comment by ankit-sanghvi** [comment]
removed the duplicate messages and replace the cancel link

**Comment by rahul-kumar11** [comment]
retested and passed
