### ISSUE TITLE
The text marked in image is not according to the design doc on Message screen. Please change the mark text.

### ISSUE THREAD

**Issue by rahul-kumar11** [subrata1106/Release17#27]
The text marked in image is not according to the design doc on Message screen. Please change the mark text.
![14](https://cloud.githubusercontent.com/assets/7794513/8208956/e4f1eb38-1527-11e5-82b9-c115ef16c244.png)

**Comment by besiddharth** [comment]
Fixed.
Cause : Inadequate Self Review

**Comment by rahul-kumar11** [comment]
retested and passed
