### ISSUE TITLE
If a user is on my info page and the user try to update his username with a username that is already register for another user. The error message is displayed globaly. The error message should be displayed inline to the username text box.

### ISSUE THREAD

**Issue by rahul-kumar11** [subrata1106/Release17#28]
If a user is on my info page and the user try to update his username with a username that is already register for another user. The error message is displayed globaly. The error message should be displayed inline to the username text box.
![15](https://cloud.githubusercontent.com/assets/7794513/8228705/88d52a16-15ce-11e5-89bd-ac3923e5de76.png)

**Comment by rahul-kumar11** [comment]
On my info page the email text box is not mandatory so if the user remove the email address then the "enter email address" error message should not be displayed.

**Comment by ankit-sanghvi** [comment]
already fixed

**Comment by rahul-kumar11** [comment]
retested and passed
