### ISSUE TITLE
The text marked in image is not according to the design doc on splash screen. Please change the mark text.

### ISSUE THREAD

**Issue by rahul-kumar11** [subrata1106/Release17#29]
The text marked in image is not according to the design doc on splash screen. Please change the mark text.
![16](https://cloud.githubusercontent.com/assets/7794513/8229033/0e4af002-15d1-11e5-8fd5-01b317d6e16e.png)

**Comment by JB-PATEL** [comment]
Fixed.
Design change

**Comment by rahul-kumar11** [comment]
retested and fixed
