### ISSUE TITLE
If user course licence has expired, and user launch the course first time, user gets the "renew licence or access as read only" screen. The screen does not show any active class in left menu. Please chnage the text marked in images as in design doc.

### ISSUE THREAD

**Issue by rahul-kumar11** [subrata1106/Release17#30]
If user course licence has expired, and user launch the course first time, user gets the "renew licence or access as read only" screen. The screen does not show any active class in left menu. Please chnage the text marked in images as in design doc.
![18](https://cloud.githubusercontent.com/assets/7794513/8230154/22f17bde-15db-11e5-9d9c-6df7cc32ddb0.png)

**Comment by jainsmriti** [comment]
Fixed the changes except the 'Renew licence' header. In the design doc the 'L' in licence is capital on this page only. For all other renew licence related pages the 'L' is small. please clarify if i should keep the 'L' small or make it capital.

**Comment by jainsmriti** [comment]
Kept the 'L' small as discussed with Nitin.

**Comment by rahul-kumar11** [comment]
retested and passed
