### ISSUE TITLE
The text marked in image is not according to the design doc on "renw licence" screen. Please change the mark text.

### ISSUE THREAD

**Issue by rahul-kumar11** [subrata1106/Release17#31]
The text marked in image is not according to the design doc on "renw licence" screen. Please change the mark text.
![19](https://cloud.githubusercontent.com/assets/7794513/8230330/e5c405ea-15dc-11e5-9c8d-10627d7a4ddd.png)

**Comment by jainsmriti** [comment]
Fixed.

**Comment by rahul-kumar11** [comment]
smriti , I think the text with course name is not bold, Please consult nitin about this.

**Comment by jainsmriti** [comment]
Fixed.

**Comment by rahul-kumar11** [comment]
retested and passed
