### ISSUE TITLE
If a user is a self register user, enter a teacher joining code of a class. User becomes teacher in that org. Class does not contain any course. If user click on manage classes user gets the exception.

### ISSUE THREAD

**Issue by rahul-kumar11** [subrata1106/Release17#32]
If a user is a self register user, enter a teacher joining code of a class. User becomes teacher in that org. Class does not contain any co
![20](https://cloud.githubusercontent.com/assets/7794513/8231656/aab62acc-15e7-11e5-8989-9c9c48e1e150.png)
urse. If user click on manage classes user gets the exception.

**Comment by ankit-sanghvi** [comment]
new viewbag value were not there, fix and commit

**Comment by rahul-kumar11** [comment]
retested and passed
