### ISSUE TITLE
If user enter the valid access code on "Enter an access code " screen and click on "continue". The user is redirected to the "use your course with a class " screen. Now if user enter an invalid joining code then user will get the error "The joining code you have entered is encorrect. Please try again". But the screen is changed to "Enter a joing code" which comes after clicking on Join class.

### ISSUE THREAD

**Issue by rahul-kumar11** [subrata1106/Release17#34]
If user enter the valid access code on "Enter an access code " screen and click on "continue". The user is redirecteced to the "use your course with a class " screen. Now if user enter an invalid joining code then user will get the error "The joining code you have entered is encorrect. Please try again". But the screen is changed to "Enter a joing code" which comes after clicking on Join class.

**Comment by rahul-kumar11** [comment]
If user enter the valid access code on "Enter an access code " screen and click on "continue". The user is redirected to the "use your course with a class " screen. The screen has cancel button but it should be link

**Comment by besiddharth** [comment]
Routing has been fixed now but complete implementation will happen when Vranda checks in the blocking code in Access Content flow. Hence, Assigning to Vranda.

**Comment by VrandaNagar** [comment]
Fixed.

**Comment by rahul-kumar11** [comment]
retested and passed
