### ISSUE TITLE
If user click on a ourse title that he is not activated, the user gets the "enter the access code screen" user put the another course acess code, user gets the error "The access ocde is not for this course. Please contact your teacher.". Now user click on join class or any other link. Then user click on "access content". The user still gets the same error message.

### ISSUE THREAD

**Issue by rahul-kumar11** [subrata1106/Release17#35]
If user click on a ourse title that he is not activated, the user gets the "enter the access code screen" user put the another course acess code, user gets the error "The access ocde is not for this course. Please contact your teacher.". Now user click on join class or any other link. Then user click on "access content". The user still gets the same error message.

**Comment by jainsmriti** [comment]
Fixed.

**Comment by rahul-kumar11** [comment]
retested and passed
