### ISSUE TITLE
The text marked in image is not according to the design doc on "Register an organization" screen. Please change the mark text.

### ISSUE THREAD

**Issue by rahul-kumar11** [subrata1106/Release17#39]
The text marked in image is not according to the design doc on "Register an organization" screen. Please change the mark text.
![22](https://cloud.githubusercontent.com/assets/7794513/8254091/18c1ad54-16b3-11e5-96bd-aed008a1cb77.png)

**Comment by jainsmriti** [comment]
Fixed.

**Comment by rahul-kumar11** [comment]
Please remove the space ......

**Comment by jainsmriti** [comment]
Removed the sapce.

**Comment by rahul-kumar11** [comment]
retested and passed
