### ISSUE TITLE
The message "Please enter valid username" was not presnt on "Sign in" page. Is this a bug or enhansement ?

### ISSUE THREAD

**Issue by rahul-kumar11** [subrata1106/Release17#4]
Steps:-
1-Do not enter any thing click on "Sign In " .
2-Error message will be displayed in line 1- Please enter your username 2- please enter password
3-Now when user click on username text box and try try to edit it and type 1 word a message "Please enter valid username." will be displayed.
This message was not earlier on sign screen.

**Comment by NitinLeuva** [comment]
Please keep it as it is in UAT and live.

**Comment by rahul-kumar11** [comment]
Dear siddharth, 
Please do the change according to the above comment.

**Comment by besiddharth** [comment]
Fixed.

**Comment by rahul-kumar11** [comment]
retested and passed
