### ISSUE TITLE
If a user enter invalid code in the , authorization code text box on "register an origination" page, then user gets the error message"The code you have entered is incorrect. Please check it and try again". Now user again click on "Enter" then there are two error message displayed at the same time.

### ISSUE THREAD

**Issue by rahul-kumar11** [subrata1106/Release17#40]
If a user enter invalid code in the , authorization code text box on "register an origination" page, then user gets the error message"The code you have entered is incorrect. Please check it and try again". Now user again click on "Enter" then there are two error message displayed at the same time.
![23](https://cloud.githubusercontent.com/assets/7794513/8255232/17bd24d4-16bc-11e5-9592-f2ca8660825d.png)

**Comment by jainsmriti** [comment]
Fixed.

**Comment by rahul-kumar11** [comment]
retested and passed
