### ISSUE TITLE
The text marked in image is not according to the design doc on "Apply for an organization account" screen. Please change the mark text.

### ISSUE THREAD

**Issue by rahul-kumar11** [subrata1106/Release17#41]
The text marked in image is not according to the design doc on "Apply for an organization account" screen. Please change the mark text.
![untitled](https://cloud.githubusercontent.com/assets/7794513/8255601/b8c8a658-16be-11e5-8227-52dadbda82ac.png)

**Comment by rahul-kumar11** [comment]
Also the error is not coming properly

**Comment by jainsmriti** [comment]
Fixed.

**Comment by rahul-kumar11** [comment]
terms and condition text is not acc to design doc.

**Comment by jainsmriti** [comment]
Changed the Terms and condition text.

**Comment by rahul-kumar11** [comment]
retested and passed
