### ISSUE TITLE
The system does not find the "application" sent screen. The system returns 404 resource not found.

### ISSUE THREAD

**Issue by rahul-kumar11** [subrata1106/Release17#42]
The system does not find the "application" sent screen. The system returns 404 resource not found.
![26](https://cloud.githubusercontent.com/assets/7794513/8255825/57f5bb2a-16c0-11e5-9b2b-a4e1d4c3ce5f.png)

**Comment by jainsmriti** [comment]
Fixed.

**Comment by rahul-kumar11** [comment]
retested and passed
