### ISSUE TITLE
If a user launch the course and that course licence validity hit any miles stone. The "notify on course launch " is true the user gets the pop up. But behind pop up there are some screen. The user stile sees the my home screen

### ISSUE THREAD

**Issue by rahul-kumar11** [subrata1106/Release17#43]
If a user launch the course and that course licence validity hit any miles stone. The "notify on course launch " is true the user gets the pop up. But behind pop up there are some screen. The user stile sees the my home screen behind the pop up.
![27](https://cloud.githubusercontent.com/assets/7794513/8276772/e905ae7c-18d7-11e5-9fe6-2c8632d4b5ae.png)

**Comment by jainsmriti** [comment]
Fixed.

**Comment by rahul-kumar11** [comment]
retested and passed
