### ISSUE TITLE
The text marked in image is not according to the design doc on "add notification" screen. Please change the mark text.

### ISSUE THREAD

**Issue by rahul-kumar11** [subrata1106/Release17#45]
The text marked in image is not according to the design doc on "add notification" screen. Please change the mark text.
![28](https://cloud.githubusercontent.com/assets/7794513/8280548/e051f0be-18fb-11e5-974a-931d118f7ef8.png)

**Comment by besiddharth** [comment]
Fixed.
Cause : Inadequate Self Review

**Comment by rahul-kumar11** [comment]
retested and passed
