### ISSUE TITLE
User is getting exception while editing any sent notification.

### ISSUE THREAD

**Issue by rahul-kumar11** [subrata1106/Release17#47]
![29](https://cloud.githubusercontent.com/assets/7794513/8280731/b8a6e8c4-18fd-11e5-9855-8c3c49fc388a.png)
User is getting exception while editing any sent notification.

**Comment by besiddharth** [comment]
Fixed by adding new resource key.
Cause : Inadequate Checklist

**Comment by rahul-kumar11** [comment]
retested AND PASSED
