### ISSUE TITLE
If a user has created the new org, the org does not have any teacher or any class. The org admin try to add notification by selecting all teacher as send to option. The user gets the error message "No user found". This message should be displayed on "add notification" pop up as in old system.

### ISSUE THREAD

**Issue by rahul-kumar11** [subrata1106/Release17#49]
If a user has created the new org, the org does not have any teacher or any class. The org admin try to add notification by selecting all teacher as send to option. The user gets the error message "No user found". This message should be displayed on "add notification" pop up as in old system.

same for the "class" option.

**Comment by besiddharth** [comment]
Unable to reproduce.

**Comment by rahul-kumar11** [comment]
closed as unable to reproduced
