### ISSUE TITLE
System taking space as a value in text box.

### ISSUE THREAD

**Issue by rahul-kumar11** [subrata1106/Release17#5]
Steps:-
1- Clcik on register link. Register page will open.
2- Do not enter any value in any field and click on "Register".
3- All the error message will be displayed inline.
4- Clikc on "Full name" text box and enter an space . The error message "Please enter Full name" will disappear.
The system should still show an error.

**Comment by dharamveerSanodiya** [comment]
White space removal applied in Full registration, Partial registration and Login page.
Suggestion

**Comment by rahul-kumar11** [comment]
retested and passed
