### ISSUE TITLE
If a user a teacher and he is not present in any class, and he try to add the notification then the user gets a global message that he is not present in any class. The user should get this message on pop up with "ok" button. If user click on "Ok" user should redirected to message scree.

### ISSUE THREAD

**Issue by rahul-kumar11** [subrata1106/Release17#50]
If a user a teacher and he is not present in any class, and he try to add the notification then the user gets a global message that he is not present in any class. The user should get this message on pop up with "ok" button. If user click on "Ok" user should redirected to message scree.

**Comment by besiddharth** [comment]
Fix.
Cause : Inadequate Self Review

**Comment by rahul-kumar11** [comment]
retested and passed
