### ISSUE TITLE
User does not gets the notification on just refreshing the message page.

### ISSUE THREAD

**Issue by rahul-kumar11** [subrata1106/Release17#51]
User does not gets the notification on just refreshing the message page.

If a user is a student in a org and has teacher or greater role  in the other org. Then he gets the teacher notification of the org in which he is a student.

**Comment by besiddharth** [comment]
Duplicate of #49

**Comment by besiddharth** [comment]
Fixed.
Cause : Inadequate CheckList

**Comment by rahul-kumar11** [comment]
retested and passed
