### ISSUE TITLE
If a user join a class by student joining code, and user is not part of the org in which that class exits. then the user will gets the org defined field. If user fill all the org defined field and click on "continue" then user gets the exception.

### ISSUE THREAD

**Issue by rahul-kumar11** [subrata1106/Release17#52]
If a user join a class by student joining code, and user is not part of the org in which that class exits. then the user will gets the org defined field. If user fill all the org defined field and click on "continue" then user gets the exception.

**Comment by jainsmriti** [comment]
Fixed.

**Comment by rahul-kumar11** [comment]
retested and passed
