### ISSUE TITLE
If user try to join a archived class the message "You cannot join an archived class. Please speak to your teacher. " is displayed. "cannot" should have "can not".

### ISSUE THREAD

**Issue by rahul-kumar11** [subrata1106/Release17#55]
If user try to join a archived class the message "You cannot join an archived class. Please speak to your teacher. " is displayed. "cannot" should have "can not".

**Comment by besiddharth** [comment]
It has be based on the language pack provided by client.

**Comment by rahul-kumar11** [comment]
language pack issue
