### ISSUE TITLE
If a class does not have any teacher and any user has activated any course of that class and try to launch it, then user gets the pop up which is currently not modified and my home is in background.

### ISSUE THREAD

**Issue by rahul-kumar11** [subrata1106/Release17#56]
If a class does not have any teacher and any user has activated any course of that class and try to launch it, then user gets the pop up which is currently not modified and my home is in background.

**Comment by rahul-kumar11** [comment]
![30](https://cloud.githubusercontent.com/assets/7794513/8304905/c565cdc6-19c7-11e5-8b78-1f2acb6149b7.png)

**Comment by JB-PATEL** [comment]
Fixed.

**Comment by rahul-kumar11** [comment]
retested and passed

**Comment by rahul-kumar11** [comment]
OK button is not working on the pop up

**Comment by JB-PATEL** [comment]
Fixed. Please re-test.

**Comment by rahul-kumar11** [comment]
retested and pass
