### ISSUE TITLE
If a user has joined the org as org admin or teacher admin, user does not get  the org select box before my info link.

### ISSUE THREAD

**Issue by rahul-kumar11** [subrata1106/Release17#57]
If a user has joined the org as org admin or teacher admin, user does not get  the org select box before my info link.
If user joined two org one as org admin and one as teacher admin he can not can the org.

**Comment by vanrajsinh-parmar** [comment]
Cause of issue: Original code was deleted with wrong check-in ID: 14277

To resolve issue, code again added.

**Comment by vanrajsinh-parmar** [comment]
Resolved. Please test again.

**Comment by rahul-kumar11** [comment]
retested and passed
