### ISSUE TITLE
If user click on refresh code on Administrator joining codes, then the pop up is displayed, if user click on "cancel" the user gets the"Administrator joining codes" screen but the codes and "org name " will not be displayed.

### ISSUE THREAD

**Issue by rahul-kumar11** [subrata1106/Release17#59]
If user click on refresh code on Administrator joining codes, then the pop up is displayed, if user click on "cancel" the user gets the"Administrator joining codes" screen but the codes and "org name " will not be displayed.

**Comment by vanrajsinh-parmar** [comment]
Resolved.
Cause: Others (wrong code due to copy-paste)

**Comment by rahul-kumar11** [comment]
retested and passed
