### ISSUE TITLE
On full registration page there are two error message displayed at a time for a field "Confirm Password".

### ISSUE THREAD

**Issue by rahul-kumar11** [subrata1106/Release17#6]
On full registration page there are two error message displayed at a time for a field "Confirm registration".
![1](https://cloud.githubusercontent.com/assets/7794513/7932664/8c5cf158-0937-11e5-96fc-1c3d2d6a0a6e.png)

**Comment by dharamveerSanodiya** [comment]
Changes done for confirm password field. Please check.
Cause - Suggestions

**Comment by rahul-kumar11** [comment]
retested and passed
