### ISSUE TITLE
The text marked in image is not according to the design doc on "Manage User" screen. Please change the mark text.

### ISSUE THREAD

**Issue by rahul-kumar11** [subrata1106/Release17#61]
The text marked in image is not according to the design doc on "Manage User" screen. Please change the mark text.
![31](https://cloud.githubusercontent.com/assets/7794513/8327944/ec47b64e-1a89-11e5-962f-56d4c0880b2e.png)

**Comment by ankit-sanghvi** [comment]
updated the resouce text

**Comment by rahul-kumar11** [comment]
retested and passed
