### ISSUE TITLE
One one user "manage class for this user" will be displayed once. 

### ISSUE THREAD

**Issue by rahul-kumar11** [subrata1106/Release17#62]
One one user "manage class for this user" will be displayed once. 
![32](https://cloud.githubusercontent.com/assets/7794513/8328038/f8078a8a-1a8a-11e5-8102-1e3d5f725b37.PNG)

**Comment by ankit-sanghvi** [comment]
fixed the position, as it was placed in loop.

**Comment by rahul-kumar11** [comment]
mnage user for this class should come the org admin not for CS admin.

**Comment by ankit-sanghvi** [comment]
fixed

**Comment by rahul-kumar11** [comment]
retested and passed
