### ISSUE TITLE
Import new Class : Please change the marked text as per new UX.

### ISSUE THREAD

**Issue by jainsmriti** [subrata1106/Release17#63]
![import new class](https://cloud.githubusercontent.com/assets/12691744/8328056/149c9c12-1a8b-11e5-9c3e-b13b891d4c8c.png)

**Comment by dharamveerSanodiya** [comment]
Suggestion implemented.

**Comment by jainsmriti** [comment]
The modified screen for this page is not provided in design doc. In the mockup also this page is not available. Have compared this screen with the mockup for Import User.

![import_new_user](https://cloud.githubusercontent.com/assets/12691744/8448838/6756db44-1fe9-11e5-9d2c-a5166ed2c2aa.png)


Please suggest if the this page has to have the text and spaces as per the "Import new User" page or not ??

**Comment by dharamveerSanodiya** [comment]
As discussed with nitin, system message should be the same.
So manage class screen and its message will be different from manage user screen.
Cause : Clarification

**Comment by jainsmriti** [comment]
Please set the spacing as per the mockup. The text would remain the same.

**Comment by dharamveerSanodiya** [comment]
Updated as per the suggestion.

**Comment by jainsmriti** [comment]
Retested and passed.
