### ISSUE TITLE
Please change on the marked text in image on manage user show details

### ISSUE THREAD

**Issue by rahul-kumar11** [subrata1106/Release17#64]
Please change on the marked text in image on manage user show details
![33](https://cloud.githubusercontent.com/assets/7794513/8328199/460a8a88-1a8c-11e5-83b0-df1ff7af4712.png)

**Comment by rahul-kumar11** [comment]
Please check with mock up. Text access code or licence  comes in a row for all classes.
Please check mock up

**Comment by JB-PATEL** [comment]
fixed.

**Comment by rahul-kumar11** [comment]
retested and passed
