### ISSUE TITLE
The text marked in image is not according to the design doc on "Create new User" screen. Please change the mark text. 

### ISSUE THREAD

**Issue by rahul-kumar11** [subrata1106/Release17#66]
The text marked in image is not according to the design doc on "Create new User" screen. Please change the mark text. 
![34](https://cloud.githubusercontent.com/assets/7794513/8329362/7bc425c6-1a96-11e5-9097-ca7849ab17e1.png)

**Comment by ankit-sanghvi** [comment]
udpated the resource text and change the client validation

**Comment by rahul-kumar11** [comment]
* mandatory should be *Required. 
Please enter an email address. "email address" is black.
Check boxex are small.
send an email ="email sign in details"

**Comment by JB-PATEL** [comment]
fixed.

**Comment by ankit-sanghvi** [comment]
updated

**Comment by rahul-kumar11** [comment]
retested and paased
