### ISSUE TITLE
Licence distribtion by Org Admin : Workflow not Working

### ISSUE THREAD

**Issue by jainsmriti** [subrata1106/Release17#69]
Orgadmin goes to Manage Classes -> Edit Class -> Edit Course : There the Orgadmin may give licence to its organization's student. This work flow for Licence distribution is not working.

**Comment by ankit-sanghvi** [comment]
its due to jquery version conflict, the function of licensing was not working

**Comment by jainsmriti** [comment]
Retested and passed.
