### ISSUE TITLE
The text marked in image should come in different languages as these text already coming different languages on UAT.

### ISSUE THREAD

**Issue by rahul-kumar11** [subrata1106/Release17#7]
The text marked in image should come in different languages as these text already coming different languages on UAT.
![2](https://cloud.githubusercontent.com/assets/7794513/7932922/269d8164-0939-11e5-997f-b12763185cd9.png)

**Comment by besiddharth** [comment]
The text is different from the current one. Hence, it should be treated as new and language pack changes should come from client end. for rest, where ever applicable , it has been changed.
Cause : Inadequate Self Reviews

**Comment by rahul-kumar11** [comment]
retested and passed
