### ISSUE TITLE
If a user try to add user in class by "add user to classes" from manage user screen then the user is redirected to mange class screen. The list of classes is displayed there. User can click on edit class link. The edit link should be disabled or not appear here.(as in old functionality").

### ISSUE THREAD

**Issue by rahul-kumar11** [subrata1106/Release17#71]
If a user try to add user in class by "add user to classes" from manage user screen then the user is redirected to mange class screen. The list of classes is displayed there. User can click on edit class link. The edit link should be disabled or not appear here.(as in old functionality").

**Comment by ankit-sanghvi** [comment]
its as same in UAT
