### ISSUE TITLE
If a user try to add user in class by "add user to classes" from manage user screen then the user is redirected to mange class screen. The list of classes is displayed there. Do not select any class and click on "add", the page get refreshed and no error message is displayed. The error message should be displayed here.

### ISSUE THREAD

**Issue by rahul-kumar11** [subrata1106/Release17#73]
If a user try to add user in class by "add user to classes" from manage user screen then the user is redirected to mange class screen. The list of classes is displayed there. Do not select any class and click on "add", the page get refreshed and no error message is displayed. The error message should be displayed here.

**Comment by ankit-sanghvi** [comment]
fixed

**Comment by rahul-kumar11** [comment]
retested and fixed
