### ISSUE TITLE
If a user try to add user in class by "add user to classes" from manage user screen then the user is redirected to mange class screen. The list of classes is displayed there. There is "add" button on the page but cancel button is missing on the page.Cancel button should be there.

### ISSUE THREAD

**Issue by rahul-kumar11** [subrata1106/Release17#74]
If a user try to add user in class by "add user to classes" from manage user screen then the user is redirected to mange class screen. The list of classes is displayed there. There is "add" button on the page but cancel button is missing on the page.Cancel button should be there.

**Comment by ankit-sanghvi** [comment]
placed the cancel link

**Comment by rahul-kumar11** [comment]
retested and passed
