### ISSUE TITLE
Teacher enters the access code on behalf of the student user. Now when the student login in the system and try to launch the course user is getting the old pop up with my account in back ground. Please check 36 image in the image folder. 

### ISSUE THREAD

**Issue by rahul-kumar11** [subrata1106/Release17#77]
Teacher enters the access code on behalf of the student user. Now when the student login in the system and try to launch the course user is getting the old pop up with my account in back ground. Please check 36 image in the image folder. 
![36](https://cloud.githubusercontent.com/assets/7794513/8348854/9e796956-1b35-11e5-90e7-00a952bab7ef.png)

**Comment by besiddharth** [comment]
Fixed.
Cause: Inadequate Documentation

**Comment by rahul-kumar11** [comment]
retested and passed
