### ISSUE TITLE
if a org admin update an user and user is updated successfully now user click on manage user then the display name of the user will not be displayed. May be User details is not  updated in Solar.

### ISSUE THREAD

**Issue by rahul-kumar11** [subrata1106/Release17#79]
if a org admin update an user and user is updated successfully now user click on manage user then the display name of the user will not be displayed. May be User details is not  updated in Solar.

**Comment by dharamveerSanodiya** [comment]
Changes incorporated as per the comments.

**Comment by rahul-kumar11** [comment]
retested and passed
