### ISSUE TITLE
Test marked with red in image is not according to the design doc.  

### ISSUE THREAD

**Issue by rahul-kumar11** [subrata1106/Release17#8]
Test marked with red in image is not according to the design doc.  
![3](https://cloud.githubusercontent.com/assets/7794513/7933618/ff8a3b80-093d-11e5-9db8-aa02d5ad1b81.png)

**Comment by besiddharth** [comment]
This was the initial layout. Later on it has been corrected by resolving the confilct with existing stylesheet.
Cause: Inadequate Documentation

**Comment by rahul-kumar11** [comment]
retested and passed
