### ISSUE TITLE
In Edit Class, If a user selects Distribute login details with more than 1 user such that some of the users have Emails and others don't. In this case the user is given a  Message "Selected user doesn't have an email address." even though some of the selected users have emails.

### ISSUE THREAD

**Issue by jainsmriti** [subrata1106/Release17#80]
In Edit Class, If a user selects Distribute login details with more than 1 user such that some of the users have Emails and others don't. In this case the user is given a  Message "Selected user doesn't have an email address." even though some of the selected users have emails.

**Comment by rahul-kumar11** [comment]
Existing closed
