### ISSUE TITLE
If an org admin create a user and select role as student then the "user id" text box will be displayed in old system but current system does not show this text box. The user id text box should be displayed if the role is selected as student on create new user screen.

### ISSUE THREAD

**Issue by rahul-kumar11** [subrata1106/Release17#81]
If an org admin create a user and select role as student then the "user id" text box will be displayed in old system but current system does not show this text box. The user id text box should be displayed if the role is selected as student on create new user screen.

**Comment by dharamveerSanodiya** [comment]
Bug resolved, please check.

**Comment by rahul-kumar11** [comment]
retested and passed
