### ISSUE TITLE
The text marked in image is not according to the design doc on "Edit user details " screen. Please change the mark text. 

### ISSUE THREAD

**Issue by rahul-kumar11** [subrata1106/Release17#82]
The text marked in image is not according to the design doc on "Edit user details " screen. Please change the mark text. 
![35](https://cloud.githubusercontent.com/assets/7794513/8351702/f6f034a4-1b4c-11e5-8583-81eee893931f.png)

**Comment by JB-PATEL** [comment]
Fixed.

**Comment by rahul-kumar11** [comment]
Required text is not present and cancel should be a link.

**Comment by JB-PATEL** [comment]
fixed.

**Comment by rahul-kumar11** [comment]
On edit user detail if role of the user is student then the org defined field must be displayed.

**Comment by rahul-kumar11** [comment]
closed
