### ISSUE TITLE
If user click on "my info" and click on "save" user gets the exception.

### ISSUE THREAD

**Issue by rahul-kumar11** [subrata1106/Release17#83]
If user click on "my info" and click on "save" user gets the exception.
![38](https://cloud.githubusercontent.com/assets/7794513/8352050/c99098d4-1b4f-11e5-92ae-ac19ef1eb8a0.png)

**Comment by rahul-kumar11** [comment]
To reproduce the bug.
qstudent16@mailinator.com
Password@123

**Comment by rahul-kumar11** [comment]
While creating the user it is not picking up the time zone

**Comment by ankit-sanghvi** [comment]
- fixed, its because of diff list was binded to timezone dropdown

**Comment by rahul-kumar11** [comment]
retested and passed
