### ISSUE TITLE
If cs admin try to edit a user he gets the exception. Not for all the users but for some users.

### ISSUE THREAD

**Issue by rahul-kumar11** [subrata1106/Release17#85]
If cs admin try to edit a user he gets the exception. Not for all the users but for some users.

Qa user:
username:-qstudent5@mailinator.com

**Comment by dharamveerSanodiya** [comment]
Not able to reproduce in dev environment. May be there is some data issue.
Please valdate and let me know.

**Comment by rahul-kumar11** [comment]
retested and passed
