### ISSUE TITLE
If Cs admin try to create a user and does not fill any data and click on create he will get only one message "Please enter Username" and now user fill and data in name text box and click on "create" Cs admin will get the exception.

### ISSUE THREAD

**Issue by rahul-kumar11** [subrata1106/Release17#86]
If Cs admin try to create a user and does not fill any data and click on create he will get only one message "Please enter Username" and now user fill and data in name text box and click on "create" Cs admin will get the exception.
![40](https://cloud.githubusercontent.com/assets/7794513/8354500/2bce77d0-1b66-11e5-94c7-80225bcac2e4.png)

**Comment by dharamveerSanodiya** [comment]
Bug is resolved. Please validate.
Hybrid page validation - Jquery conflicts+ included validate script into the solution.

**Comment by rahul-kumar11** [comment]
retested and passed
