### ISSUE TITLE
The title in the File Import Status redirecting to a separate page

### ISSUE THREAD

**Issue by jainsmriti** [subrata1106/Release17#87]
![import_class_links](https://cloud.githubusercontent.com/assets/12691744/8373824/ca4b0b6a-1c0d-11e5-8fa8-be2e8ed0c345.png)
![redirected page](https://cloud.githubusercontent.com/assets/12691744/8373826/cc1c576e-1c0d-11e5-81ba-62ce214c6f95.png)

**Comment by rahul-kumar11** [comment]
Same in case of import user.

**Comment by dharamveerSanodiya** [comment]
Sorting removed from import user and class grid. Please validate.

**Comment by jainsmriti** [comment]
Retested and closed.
