### ISSUE TITLE
If a user try to archive a record on import new user screen then,  the record will not be archived.

### ISSUE THREAD

**Issue by rahul-kumar11** [subrata1106/Release17#88]
If a user try to archive a record on import new user screen then,  the record will not be archived.

In IE and firebox the pop is displayed but in chrome pop is not displayed.

**Comment by dharamveerSanodiya** [comment]
Bug resolved. Please check.
Inadequate Checklist

**Comment by rahul-kumar11** [comment]
retested and passed
