### ISSUE TITLE
If org admin edit a user details and click on "save" he gets the "edit user" pop up. If he click on "ok" on pop up user is redirected on the create new user screen. User should be redirected to the edit user details screen.

### ISSUE THREAD

**Issue by rahul-kumar11** [subrata1106/Release17#89]
If org admin edit a user details and click on "save" he gets the "edit user" pop up. If he click on "ok" on pop up user is redirected on the create new user screen. User should be redirected to the edit user details screen.

**Comment by ankit-sanghvi** [comment]
- fixed the redirection

**Comment by rahul-kumar11** [comment]
retested and passed
