### ISSUE TITLE
Header of sign in page is working properly when user "zoom in " or "zoom out" the page.

### ISSUE THREAD

**Issue by rahul-kumar11** [subrata1106/Release17#9]
Header of sign in page is working properly when user "zoom in " or "zoom out" the page
![4](https://cloud.githubusercontent.com/assets/7794513/8158032/0f3d374c-1377-11e5-950e-d4d79d262b0a.png)
.

**Comment by besiddharth** [comment]
It was not working in the HTML mockup provided as well. Hence, corrected as part of value edition.

**Comment by rahul-kumar11** [comment]
retested and passed
