### ISSUE TITLE
The text marked in image is not according to the design doc on "Import new user " screen. Please change the mark text. 

### ISSUE THREAD

**Issue by rahul-kumar11** [subrata1106/Release17#90]
The text marked in image is not according to the design doc on "Import new user " screen. Please change the mark text. 
![41](https://cloud.githubusercontent.com/assets/7794513/8374406/bbf5cfdc-1c12-11e5-81df-f276d53587b1.PNG)

**Comment by JB-PATEL** [comment]
fixed.
Input File control text and style are controlled by browser. No changes can be done for it.

**Comment by rahul-kumar11** [comment]
retested and passed
