### ISSUE TITLE
Email template select box on create new user screen will be displayed when the "send en email" check box is checked. But in the current system if there are more then two template the text is displayed without check the send email check box.

### ISSUE THREAD

**Issue by rahul-kumar11** [subrata1106/Release17#91]
Email template select box on create new user screen will be displayed when the "send en email" check box is checked. But in the current system if there are more then two template the text is displayed without check the send email check box.

**Comment by ankit-sanghvi** [comment]
- fixed the same script issue.

**Comment by rahul-kumar11** [comment]
retested and passed
