### ISSUE TITLE
Error message on import user page should be displayed according to old system.

### ISSUE THREAD

**Issue by rahul-kumar11** [subrata1106/Release17#92]
1- On import new user  if user does not choose any file and click on import , the error message should be displayed on the same page.
2- If user select any other format file then user get the error message on the same page.
3- If file does not have valid entries in file the error message should be displayed on the next page but with the line " The following error message occurs." and user should not able to delete the error message. (Remove cross from the error message")
4- Please change "back" button to cancel link on the error page.

**Comment by JB-PATEL** [comment]
Fixed.

**Comment by rahul-kumar11** [comment]
retested and fixed
