### ISSUE TITLE
If user join a OTA course in self study the course should be launched after the process but user is redirected to my course in the current system.

### ISSUE THREAD

**Issue by rahul-kumar11** [subrata1106/Release17#93]
If user join a OTA course in self study the course should be launched after the process but user is redirected to my course in the current system.

**Comment by NitinLeuva** [comment]
I think this has been fixed last week, Sid to confirm.

**Comment by besiddharth** [comment]
Code checked in. Please validate.

**Comment by rahul-kumar11** [comment]
Flow is not correct:
Current Flow:--------access content---Selfstudy---CourseAddedScreen---OrgdefinedField---Launch
Right Flow:--------access content---Selfstudy---OrgdefinedField---CourseAddedScreen---Launch

**Comment by besiddharth** [comment]
Fixed.
Caused : Inadequate Documentation

**Comment by rahul-kumar11** [comment]
retested and passed
